table
BelohvostovAlex/tableJS pull request #1
Opened 2022-05-02 12:39 UTC by BelohvostovAlex

2022-05-04 05:04 UTC, igorTT requested changes
Replace let with const where the values are immutable.

2022-05-04 05:04 UTC, igorTT commented on script.js
> +        padding: 10px`
Broken spaces and missing semicolon

2022-05-04 05:04 UTC, igorTT commented on script.js
> +    const tbody = document.createElement("tbody");
Make a helper function that gets tag name, styles, and text content as parameters and returns an element.

2022-05-04 05:04 UTC, igorTT commented on script.js
> +      td4.textContent = user.email;
replace with helpers

2022-05-04 05:04 UTC, igorTT commented on script.js
> +  const createTable = async (thNames = ["id", "name", "phone", "website"]) => {
You're trying to make this function reusable but, you have hard coded values on the cycle 48th line

2022-05-04 05:04 UTC, igorTT commented on script.js
> +    return users;
add try ... catch

2022-05-04 05:04 UTC, igorTT commented on script.js
> +    for (let i = 0; i < thNames.length; i++) {
replace with foreach

2022-05-04 11:51 UTC, igorTT requested changes

2022-05-04 11:51 UTC, igorTT commented on script.js
> +  const createEl = (el, text, styles) => {
Pass arguments like an object. It'll help you to get rid of passing `null`, etc.

2022-05-04 11:51 UTC, igorTT commented on script.js
> +      const data = await fetchedData;
Pass this argument as a callback function. It'll make the code less confusing.

2022-05-04 11:51 UTC, igorTT commented on script.js
> +      for (let i = 0; i < allTd.length; i++) {
Replace with foreach

2022-05-04 11:51 UTC, igorTT commented on script.js
> +    try {
You don't need to catch errors in this function.

2022-05-04 11:51 UTC, igorTT commented on script.js
> +      thNames.forEach((element) => {
Replace the element with a title

2022-05-04 11:51 UTC, igorTT commented on script.js
> +      const allTd = document.querySelectorAll("td");
Why not add styles while creating components?

2022-05-04 12:11 UTC, BelohvostovAlex commented on script.js
> +      for (let i = 0; i < allTd.length; i++) {
deleted (useless)

2022-05-05 04:49 UTC, igorTT commented on script.js
> +  const createEl = (obj) => {
Don't name entities with their type. Name it like args, config etc...
Use destructuring.

2022-05-05 04:49 UTC, igorTT commented on script.js
> +        styles: `
Fix the gaps.
Configure your code editor with formatting on save.

2022-05-05 13:55 UTC, igorTT approved these changes

2022-05-05 13:55 UTC, merged